// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ECommerce.DAL.Models
{
    public partial class ProductImage
    {
        [Key]
        public int ID { get; set; }
        public int? ProductID { get; set; }
        public string Description { get; set; }
        [Required]
        public string Image { get; set; }
        public bool? ISMain { get; set; }

        [ForeignKey("ProductID")]
        [InverseProperty("ProductImages")]
        public virtual Product Product { get; set; }
    }
}